name: AWS test

on:
  workflow_dispatch:

# Need ID token write permission to use OIDC
permissions:
  id-token: write
jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main # Or a specific version
        with:
          role-to-assume: arn:aws:iam::125616717413:role/haars-deleteme
          aws-region: us-east-1
      - name: Additional steps
        run: |
          # Your commands that require AWS credentials
          aws sts get-caller-identity 
